AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  firearm-api
  A serverless FastAPI application for the FirearmDB.
  # Force update 2026-01-26 to refresh environment variables after secret rotation

Parameters:
  VpcSecurityGroupIds:
    Type: CommaDelimitedList
    Description: "Security Group IDs for the Lambda function"
  VpcSubnetIds:
    Type: CommaDelimitedList
    Description: "Subnet IDs for the Lambda function"
  StageName:
    Type: String
    Default: Prod
    Description: "The name of the API Gateway Stage"

Globals:
  Function:
    Timeout: 30

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      MethodSettings: []

  # Usage plan for anonymous users (lower limits)
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "${AWS::StackName}-AnonymousPlan"
      Description: "Usage plan for anonymous users with lower rate limits"
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref StageName
          Throttle:
            "/api/v1/token/POST":
              BurstLimit: 5
              RateLimit: 2
            "/api/v1/register/POST":
              BurstLimit: 5
              RateLimit: 2
      Throttle:
        BurstLimit: 20
        RateLimit: 10

  # API Key for authenticated users
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: ApiGatewayStage
    Properties:
      Name: !Sub "${AWS::StackName}-ApiKey"
      Description: "API Key for authenticated users"
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGateway
          StageName: !Ref StageName

  # Usage plan for authenticated users (higher limits)
  AuthenticatedUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "${AWS::StackName}-AuthenticatedPlan"
      Description: "Usage plan for API key holders with higher rate limits"
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref StageName
      Throttle:
        BurstLimit: 200
        RateLimit: 100

  # Associate API Key with authenticated usage plan
  ApiKeyUsagePlanAssociation:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref AuthenticatedUsagePlan

  FirearmApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Firearm API Lambda Function - updated 2026-01-26"
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway
        AuthToken:
          Type: Api
          Properties:
            Path: /api/v1/token
            Method: POST
            RestApiId: !Ref ApiGateway
        AuthRegister:
          Type: Api
          Properties:
            Path: /api/v1/register
            Method: POST
            RestApiId: !Ref ApiGateway
            
      VpcConfig:
        SecurityGroupIds: !Ref VpcSecurityGroupIds
        SubnetIds: !Ref VpcSubnetIds

      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - SecretsManagerReadWrite

      Environment:
        Variables:
          DB_SERVER: "{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-3:384648803631:secret:prod/firearm-api/credentials-LmfgbP:SecretString:DB_SERVER}}"
          DB_NAME: "{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-3:384648803631:secret:prod/firearm-api/credentials-LmfgbP:SecretString:DB_NAME}}"
          DB_USER: "{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-3:384648803631:secret:prod/firearm-api/credentials-LmfgbP:SecretString:DB_USER}}"
          DB_PORT: "{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-3:384648803631:secret:prod/firearm-api/credentials-LmfgbP:SecretString:DB_PORT}}"
          DB_PASSWORD: "{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-3:384648803631:secret:rds!db-fa2781de-81a7-40ba-aaa8-703270306399-EardwP:SecretString:password}}"
          SECRET_KEY: "{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-3:384648803631:secret:prod/firearm-api/secret-key-4HbG4r:SecretString:SECRET_KEY}}"
    Metadata:
      DockerTag: dev
      DockerContext: ./
      Dockerfile: Dockerfile